import csv
import os
import shutil
import time
from pathlib import Path
from threading import Thread

import pytest
import yaml
from prompt_toolkit.application import create_app_session
from prompt_toolkit.input import create_pipe_input
from prompt_toolkit.output import DummyOutput
from typer.testing import CliRunner

from deet.data_models.documents import Document
from deet.data_models.project import DeetProject, ExperimentArtefacts
from deet.processors.converter_register import SupportedImportFormat
from deet.scripts.cli import app
from deet.settings import get_settings

settings = get_settings()


@pytest.fixture
def runner():
    return CliRunner()


INTEGRATION_DATASETS = [
    Path(__file__).parent / "datasets/ebmnlp_with_metadata",
    Path(__file__).parent / "datasets/alzped",
]


@pytest.fixture(scope="module")
def tmp_project_workspace(tmp_path_factory):
    """Create a workspace directory that persists for this module."""
    workspace_dir = tmp_path_factory.mktemp("projects")
    previous_cwd = Path.cwd()
    os.chdir(workspace_dir)
    try:
        yield workspace_dir
    finally:
        os.chdir(previous_cwd)


@pytest.fixture
def initialised_project_workspace(
    tmp_project_workspace, dataset_base_path, monkeypatch
):
    """Set up an initialised project, on which other tests depend."""
    previous_cwd = Path.cwd()

    # Pin the Azure API version to a recent version that strictly enforces the
    # "$ref cannot have sibling keywords" JSON-schema rule (Azure rejects a
    # $ref carrying a sibling `description`). Older versions (e.g.
    # 2024-02-15-preview) silently tolerate it, so without pinning the test can
    # pass against a malformed schema. Pinning the strict version makes this a
    # regression guard for the response schema generated by
    # build_llm_response_model.
    monkeypatch.setenv("AZURE_API_VERSION", "2025-02-01-preview")

    project_name = dataset_base_path.name
    project_dir = tmp_project_workspace / project_name

    if project_dir.exists():
        shutil.rmtree(project_dir)
    project_dir.mkdir(parents=True)
    os.chdir(project_dir)

    # Programmatically mock a completed wizard setup matching the dataset
    project = DeetProject(
        name=project_name,
        gold_standard_data_path=dataset_base_path / "reports.json",
        gold_standard_data_format=SupportedImportFormat.EPPI_JSON,
        pdf_dir=dataset_base_path / "pdfs",
    )
    project.setup()

    # Configure extraction to handle long documents
    config_path = project.config_path
    if config_path.exists():
        with config_path.open() as f:
            config = yaml.safe_load(f)
        config["truncate_on_overflow"] = True
        with config_path.open("w") as f:
            yaml.dump(config, f)

    try:
        yield project_dir
    finally:
        os.chdir(previous_cwd)


@pytest.fixture(scope="module")
def virtual_keyboard():
    with (
        create_pipe_input() as pipe_input,
        create_app_session(input=pipe_input, output=DummyOutput()),
    ):
        yield pipe_input


@pytest.mark.parametrize("dataset_base_path", INTEGRATION_DATASETS)
def test_initialise_project_via_wizard(
    runner, dataset_base_path, tmp_project_workspace, virtual_keyboard
):
    """Test whether Alice can initialise a project with her data using the wizard."""
    # Alice's project name is the last bit of the path to her dataset
    project_name = dataset_base_path.name

    # Alice will use a directory named after her project name in the
    # tmp_project_workspace created for testing deet
    project_dir = tmp_project_workspace / project_name

    # She checks if it exists, and removes it if it does, then creates it afresh
    # and changed into it
    original_cwd = Path.cwd()
    if project_dir.exists():
        shutil.rmtree(project_dir)
    project_dir.mkdir(parents=True)
    os.chdir(project_dir)

    time_limit = 10
    did_time_out = False

    def user_journey():
        """Replicate the keyboard strokes Alice will make when using the CLI."""
        nonlocal did_time_out
        try:
            # Alice sees an informative splash screen informing her on how to
            # use the wizard. She presses enter to continue
            virtual_keyboard.send_text("\r")
            time.sleep(0.1)
            # She selects the default dataset type option (eppijson)
            virtual_keyboard.send_text("\r")

            # Then she enters path to her dataset
            virtual_keyboard.send_text(f"{dataset_base_path / 'reports.json'}\r")
            virtual_keyboard.send_text("\r")

            # She enters the path to her pdfs
            virtual_keyboard.send_text(f"{dataset_base_path / 'pdfs'}\r")
            virtual_keyboard.send_text("\r")

            # She then sees a splash screen informing her on the collection of API keys
            virtual_keyboard.send_text("\r")

            # She leaves each unchanged
            virtual_keyboard.send_text("\r")
            virtual_keyboard.send_text("\r")

            # If things haven't finished at the end of the time limit,
            # Alice exits the wizard.
            time.sleep(time_limit)
            did_time_out = True
            virtual_keyboard.send_text("\x03")
        except OSError:
            # Safely caught when the main thread finishes successfully
            # and tears down the keyboard pipes early.
            pass

    typer_thread = Thread(target=user_journey, daemon=True)
    typer_thread.start()

    try:
        # Run natively on the main thread so CliRunner can attach to streams properly
        result = runner.invoke(app, ["project", "init"])

        assert result.exit_code == 0
        deet_project = DeetProject.load()
        assert deet_project.name == project_name

        processed_data = deet_project.process_data()
        assert len(processed_data.documents) > 0
        assert len(processed_data.attributes) > 0
        assert len(processed_data.annotated_documents) > 0

    finally:
        # Fixed: Pass your tracked path variable back to recover process state
        os.chdir(original_cwd)


@pytest.mark.parametrize("dataset_base_path", INTEGRATION_DATASETS)
def test_linking_with_map(
    runner, dataset_base_path, tmp_project_workspace, initialised_project_workspace
):
    """Test whether Alice can link documents."""
    # Alice makes sure she is in the project directory she created on project init
    project_dir = tmp_project_workspace / dataset_base_path.name
    os.chdir(project_dir)
    #  Alice adds the necessary metadata for her files to be linked
    shutil.copy(dataset_base_path / "link_map.csv", project_dir / "link_map.csv")

    result = runner.invoke(app, ["project", "link"])
    assert result.exit_code == 0

    deet_project = DeetProject.load()
    processed_data = deet_project.process_data()

    for doc in processed_data.documents:
        doc_id = doc.safe_identity.document_id
        doc_path = deet_project.linked_documents_path / f"{doc_id}.json"
        assert doc_path.exists()
        linked_doc = Document.load(doc_path)
        assert linked_doc.parsed_document is not None
        assert linked_doc.parsed_document.text != ""


def assert_llm_csv_contains_values(path: Path) -> None:
    """Validate that the LLM produced something for each doc-attribute combination."""
    with path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    assert len(rows) > 0, "CSV contains no rows."


@pytest.mark.vcr
@pytest.mark.parametrize("dataset_base_path", INTEGRATION_DATASETS)
def test_extraction_without_evaluating(
    runner,
    dataset_base_path,
    tmp_project_workspace,
    initialised_project_workspace,
    request,
):
    """Test whether Alice can extract data using the LLM."""
    # Alice makes sure she is in the project directory she created on project init
    project_dir = tmp_project_workspace / dataset_base_path.name
    os.chdir(project_dir)
    deet_project = DeetProject.load()

    #  Alice adds the necessary metadata for her files to be linked
    shutil.copy(dataset_base_path / "link_map.csv", deet_project.link_map_path)

    # Alice adds her own custom prompts for the attributes she wants to extract
    shutil.copy(
        dataset_base_path / "prompt_definitions.csv", deet_project.prompt_csv_path
    )

    # Alice links her documents
    result = runner.invoke(app, ["project", "link"])
    assert result.exit_code == 0

    # And then she runs deet experiments predict
    # to generate extractions for those documents
    # without trying to evaluate these
    result = runner.invoke(
        app, ["experiments", "predict", "--config-path", deet_project.config_path]
    )
    assert result.exit_code == 0

    # Alice makes sure her experiments dir exists
    # and that it contains a folder for her new experiment
    assert deet_project.experiments_dir.exists()
    run_dirs = list(deet_project.experiments_dir.iterdir())
    assert len(run_dirs) == 1

    # She finds the directory for the experiment she just carried out
    experiment_run_dir = run_dirs[0]
    run_id = experiment_run_dir.name

    # And makes sure it contains all the experiment artefacts she would expect
    artefacts = ExperimentArtefacts(base_dir=experiment_run_dir, run_id=run_id)

    assert artefacts.config_snapshot.exists()
    assert artefacts.prompts_snapshot.exists()
    assert artefacts.llm_annotation_csv.exists()
    assert artefacts.llm_annotations.exists()

    # She also makes sure that the csv containing llm
    # annotations is not empty
    assert_llm_csv_contains_values(artefacts.llm_annotation_csv)


@pytest.mark.vcr
@pytest.mark.parametrize("dataset_base_path", INTEGRATION_DATASETS)
def test_extraction_without_evaluating_or_linking(
    runner,
    dataset_base_path,
    tmp_project_workspace,
    initialised_project_workspace,
):
    """Test whether Alice can extract data using the LLM."""
    # Alice makes sure she is in the project directory she created on project init
    project_dir = tmp_project_workspace / dataset_base_path.name
    os.chdir(project_dir)
    deet_project = DeetProject.load()

    # Alice adds her own custom prompts for the attributes she wants to extract
    shutil.copy(
        dataset_base_path / "prompt_definitions.csv", deet_project.prompt_csv_path
    )

    result = runner.invoke(app, ["project", "link"])
    assert result.exit_code == 0

    # Alice doesn't want to bother linking yet, she just extracts directly
    # from her texts.
    result = runner.invoke(
        app,
        [
            "experiments",
            "predict",
            "--config-path",
            deet_project.config_path,
            "--ignore-references",
        ],
    )
    assert result.exit_code == 0

    # Alice makes sure her experiments dir exists
    # and that it contains a folder for her new experiment
    assert deet_project.experiments_dir.exists()
    run_dirs = list(deet_project.experiments_dir.iterdir())
    assert len(run_dirs) == 1

    # She finds the directory for the experiment she just carried out
    experiment_run_dir = run_dirs[0]
    run_id = experiment_run_dir.name

    # And makes sure it contains all the experiment artefacts she would expect
    artefacts = ExperimentArtefacts(base_dir=experiment_run_dir, run_id=run_id)

    assert artefacts.config_snapshot.exists()
    assert artefacts.prompts_snapshot.exists()
    assert artefacts.llm_annotation_csv.exists()
    assert artefacts.llm_annotations.exists()

    # She also makes sure that the csv containing llm
    # annotations is not empty
    assert_llm_csv_contains_values(artefacts.llm_annotation_csv)


@pytest.mark.vcr
@pytest.mark.parametrize("dataset_base_path", INTEGRATION_DATASETS)
def test_extraction_with_evaluation(
    runner, dataset_base_path, tmp_project_workspace, initialised_project_workspace
):
    """Test whether Alice can extract data using the LLM."""
    # Alice makes sure she is in the project directory she created on project init
    project_dir = tmp_project_workspace / dataset_base_path.name
    os.chdir(project_dir)
    deet_project = DeetProject.load()

    #  Alice adds the necessary metadata for her files to be linked
    shutil.copy(dataset_base_path / "link_map.csv", deet_project.link_map_path)

    # Alice adds her own custom prompts for the attributes she wants to extract
    shutil.copy(
        dataset_base_path / "prompt_definitions.csv", deet_project.prompt_csv_path
    )

    # Alice links her documents
    result = runner.invoke(app, ["project", "link"])
    assert result.exit_code == 0

    # And runs deet experiments evaluate to extract
    # data and compare it to her own gold-standard
    # data
    result = runner.invoke(
        app, ["experiments", "evaluate", "--config-path", deet_project.config_path]
    )
    assert result.exit_code == 0

    # Alice makes sure her experiments dir exists
    # and that it contains a folder for her new experiment
    assert deet_project.experiments_dir.exists()
    run_dirs = list(deet_project.experiments_dir.iterdir())
    assert len(run_dirs) == 1

    # She finds the directory for the experiment she just carried out
    experiment_run_dir = run_dirs[0]
    run_id = experiment_run_dir.name

    # And makes sure it contains all the experiment artefacts she would expect
    artefacts = ExperimentArtefacts(base_dir=experiment_run_dir, run_id=run_id)

    assert artefacts.config_snapshot.exists()
    assert artefacts.prompts_snapshot.exists()
    assert artefacts.comparison.exists()
    assert artefacts.llm_annotations.exists()
    assert artefacts.metrics.exists()

    # She also makes sure that the csv containing llm
    # and human annotations is not empty
    assert_llm_csv_contains_values(artefacts.comparison)
